#!/bin/bash

# Check for reboot, mail if
# reboot detected

if [ "$USER" == "" ]; then
	# When run by cron $USER
	# is not set but 
	# $LOGNAME is
	mailto=$LOGNAME
else
  mailto=$USER
fi

##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##

ltimstore=~/.$(basename $0).ltimstore

if [ "$1" == "-t" ]; then
	sed -e 's/^/1/g' -i $ltimstore
	echo ok
	exit
fi

uptim=$(cut -d. -f1 /proc/uptime)

if [ ! -r "$ltimstore" ]; then
	echo "$uptim" > "$ltimstore"
	exit
fi

luptim=$(cat "$ltimstore")
uptim=$(cut -d. -f1 /proc/uptime)
[ ${#luptim} = 0 ] && echo noluptim && exit
[ ${#uptim} = 0 ] && echo nouptim && exit
echo "$uptim" > "$ltimstore"
if [ "$luptim" -gt "$uptim" ]; then
	mail -s "SYSTEM $(hostname) HAS BEEN BOOTED!" $mailto <<EOI
SYSTEM $(hostname) HAS BEEN BOOTED!
Uptime at$(uptime)
EOI
fi
exit
