#!/bin/bash

# Send actual DSL statistic
# To be run by cron at
# 12/31 23:55 every year
# e. g. use entry
# 58 23 * 31 12 /home/pi/bin/fbendofyear

export PATH="$PATH:$HOME/bin"

y=$(date +%Y)
of=$(fbyearstat -narrow DSL-Statistik 2018)
mutt -s "$of" -a "$of" -- pi@localhost <<EOI
Servus,
hier ist $0.
Anbei die aktuelle DSL-Anschluss-Statistik für $(date +%Y).

Ciao
EOI
exit
