#!/bin/bash
##
# Author: Benno K.
# Email: benno@xyz.de
# Github: https://www.github.com/Benno-K
# 
# This script is available for
# public use under GPL V3 (see
# file LICENSE)
##
if [ "$1" = "" ];then
  read -p "Output file: " cfil
else
  cfil="$1"
fi
. ~/.fblogsrc
read -s -p "?: " word
echo -n  "$word"|ccencrypt -K "$keycc" > $cfil
exit
